name: panoptes
version: 0.0.1
description: >-
  Type utilities for dart
author: Christoph <gaoler@electronicpanopticon.com>
homepage: https://github.com/electronicpanopticon/panoptes

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.3.4